import { Lead } from "@/lib/types";

export const mockLeads: Lead[] = [
  {
    id: "lead-001",
    leadRef: "L-10021",
    title: "Lumina Architecture HQ Renovation",
    status: "New",
    urgency: "High",
    priority: "Hot",
    contactName: "Alara Kalila",
    companyName: "Gutheritale Lourdes Hospital",
    assignedTo: "Katie Allen",
    callDue: "Call due today",
    location: "New York, NY",
    contactTitle: "Senior Buyer",
    customerFor: "Medzah",
    email: "alara.k@lumina.studio",
    phone: "+1 (555) 012-3456",
    validTill: "May 15, 2024",
    expectedRevenue: "$48,500",
    grandTotal: "$52,400",
    subject: "HQ Interior Renovation – Phase 2",
    opportunityOwner: "Kevin Calamari",
    accountName: "Lumina Architecture Ltd.",
    pipeline: "Sales Pipeline",
    businessType: "B2B",
    leadSource: "Cold Call",
    skusQuantity: "14 SKUs / 320 units",
    shippingMethod: "Express Freight",
    createdDate: "Apr 2, 2024",
    note: "Client prefers communication via email. Budget confirmed for Phase 2 contingent on Phase 1 approval. Follow up before end of month.",

    activities: [
      {
        id: "act-001",
        type: "email",
        title: "Email Sent",
        description: "Introduction & Portfolio Presentation",
        timestamp: "YESTERDAY, 4:12 PM",
      },
      {
        id: "act-002",
        type: "call",
        title: "Inbound Call",
        description: "Duration: 12m 45s • Project scope discussed",
        timestamp: "OCT 24, 11:30 AM",
      },
      {
        id: "act-003",
        type: "created",
        title: "Lead Created",
        description: "Source: Cold Call",
        timestamp: "OCT 22, 09:15 AM",
      },
    ],
  },
  {
    id: "lead-002",
    leadRef: "L-10022",
    title: "Meridian Towers Fit-Out",
    status: "New",
    urgency: "Medium",
    priority: "Warm",
    contactName: "James Okonkwo",
    companyName: "Meridian Properties",
    assignedTo: "Kevin Calamari",
    location: "Chicago, IL",
    contactTitle: "Procurement Manager",
    customerFor: "Medzah",
    email: "j.okonkwo@meridian.co",
    phone: "+1 (555) 310-9201",
    validTill: "Jun 1, 2024",
    expectedRevenue: "$72,000",
    grandTotal: "$78,500",
    subject: "Office Towers Floor 4–8 Fit-Out",
    opportunityOwner: "Kevin Calamari",
    accountName: "Meridian Properties Inc.",
    pipeline: "Sales Pipeline",
    businessType: "B2B",
    leadSource: "Internal Referral",
    skusQuantity: "22 SKUs / 580 units",
    shippingMethod: "Standard",
    createdDate: "Mar 28, 2024",
    note: "Decision maker is the COO. James is the procurement lead.",
    activities: [
      {
        id: "act-004",
        type: "call",
        title: "Outbound Call",
        description: "Discussed scope and deliverables.",
        timestamp: "APR 5, 11:00 AM",
      },
      {
        id: "act-005",
        type: "created",
        title: "Lead Created",
        description: "Created from cold outreach campaign.",
        timestamp: "MAR 28, 8:45 AM",
      },
    ],
  },
  {
    id: "lead-003",
    leadRef: "L-10023",
    title: "Vantage Retail Chain Expansion",
    status: "New",
    urgency: "High",
    priority: "Hot",
    contactName: "Sofia Reyes",
    companyName: "Vantage Retail Group",
    assignedTo: "Katie Allen",
    callDue: "Call due today",
    location: "Los Angeles, CA",
    contactTitle: "Head of Procurement",
    customerFor: "Medzah",
    email: "sofia.r@vantageretail.com",
    phone: "+1 (555) 788-4450",
    validTill: "Apr 30, 2024",
    expectedRevenue: "$135,000",
    grandTotal: "$142,300",
    subject: "Multi-site retail fixtures procurement",
    opportunityOwner: "Kevin Calamari",
    accountName: "Vantage Retail Group LLC",
    pipeline: "Sales Pipeline",
    businessType: "B2B",
    leadSource: "Premier",
    skusQuantity: "35 SKUs / 1,200 units",
    shippingMethod: "Freight + Installation",
    createdDate: "Mar 10, 2024",
    note: "Urgent. Deadline tied to Q2 store opening schedule.",
    activities: [
      {
        id: "act-006",
        type: "email",
        title: "Contract Sent",
        description: "Sent final contract for review.",
        timestamp: "APR 12, 3:20 PM",
      },
      {
        id: "act-007",
        type: "note",
        title: "Internal Note",
        description: "Legal review completed, ready to proceed.",
        timestamp: "APR 11, 4:00 PM",
      },
      {
        id: "act-008",
        type: "created",
        title: "Lead Created",
        description: "Met at industry trade show.",
        timestamp: "MAR 10, 2:00 PM",
      },
    ],
  },
  {
    id: "lead-004",
    leadRef: "L-10024",
    title: "Hartwell Medical Clinic Refit",
    status: "New",
    urgency: "Low",
    priority: "Cold",
    contactName: "Dr. Emily Hartwell",
    companyName: "Hartwell Medical",
    assignedTo: "Kevin Calamari",
    callDue: "Call due in 2 days",
    location: "Boston, MA",
    contactTitle: "Medical Director",
    customerFor: "Medzah",
    email: "e.hartwell@hartwellmed.com",
    phone: "+1 (555) 602-3317",
    validTill: "May 22, 2024",
    expectedRevenue: "$29,000",
    grandTotal: "$31,750",
    subject: "Clinic waiting area + consultation rooms",
    opportunityOwner: "Kevin Calamari",
    accountName: "Hartwell Medical Centre",
    pipeline: "Sales Pipeline",
    businessType: "B2C",
    leadSource: "Chamber of Commerce",
    skusQuantity: "8 SKUs / 90 units",
    shippingMethod: "Standard",
    createdDate: "Apr 5, 2024",
    note: "Attempted 3 times via email. Left voicemail on Apr 9.",
    activities: [
      {
        id: "act-009",
        type: "call",
        title: "Voicemail Left",
        description: "Left voicemail requesting callback.",
        timestamp: "APR 9, 1:45 PM",
      },
      {
        id: "act-010",
        type: "created",
        title: "Lead Created",
        description: "Inbound inquiry via website contact form.",
        timestamp: "APR 5, 10:00 AM",
      },
    ],
  },
  {
    id: "lead-005",
    leadRef: "L-10025",
    title: "Skyline Co-working Hub Setup",
    status: "New",
    urgency: "Medium",
    priority: "Warm",
    contactName: "Nathan Blake",
    companyName: "Skyline Co-work",
    assignedTo: "Katie Allen",
    location: "Austin, TX",
    contactTitle: "Co-founder & CEO",
    customerFor: "Medzah",
    email: "n.blake@skylinecw.io",
    phone: "+1 (555) 491-2280",
    validTill: "May 10, 2024",
    expectedRevenue: "$95,000",
    grandTotal: "$103,200",
    subject: "Full fit-out for 4-floor co-working space",
    opportunityOwner: "Kevin Calamari",
    accountName: "Skyline Co-working Solutions",
    pipeline: "Sales Pipeline",
    businessType: "B2B",
    leadSource: "LinkedIn",
    skusQuantity: "28 SKUs / 760 units",

    shippingMethod: "White Glove",
    createdDate: "Mar 18, 2024",
    note: "Highly motivated buyer. Budget approved by board. Final decision due May 1.",
    activities: [
      {
        id: "act-011",
        type: "email",
        title: "Final Proposal Sent",
        description: "Sent revised proposal with updated pricing.",
        timestamp: "APR 14, 9:00 AM",
      },
      {
        id: "act-012",
        type: "call",
        title: "Discovery Call",
        description: "Completed discovery call, requirements confirmed.",
        timestamp: "APR 1, 10:00 AM",
      },
      {
        id: "act-013",
        type: "created",
        title: "Lead Created",
        description: "Via LinkedIn message campaign.",
        timestamp: "MAR 18, 11:30 AM",
      },
    ],
  },
  {
    id: "lead-006",
    leadRef: "L-10026",
    title: "Paragon Hotel Chain Sourcing",
    status: "New",
    urgency: "Medium",
    priority: "Warm",
    contactName: "Vivienne Marsh",
    companyName: "Paragon Hotels",
    assignedTo: "Kevin Calamari",
    location: "Miami, FL",
    contactTitle: "VP of Operations",
    customerFor: "Medzah",
    email: "v.marsh@paragonhotels.com",
    phone: "+1 (555) 838-7745",
    validTill: "Jul 15, 2024",
    expectedRevenue: "$220,000",
    grandTotal: "$238,500",
    subject: "Rooms 201–450 furniture procurement – Phase 1",
    opportunityOwner: "Kevin Calamari",
    accountName: "Paragon Hotel Group",
    pipeline: "Sales Pipeline",
    businessType: "B2B",
    leadSource: "External Referral",
    skusQuantity: "18 SKUs / 2,250 units",
    shippingMethod: "Bulk Freight",
    createdDate: "Feb 20, 2024",
    note: "On hold due to internal restructuring. Resume in Q3.",
    activities: [
      {
        id: "act-014",
        type: "note",
        title: "Status Change",
        description: "Placed on hold per client request.",
        timestamp: "APR 7, 2:00 PM",
      },
      {
        id: "act-015",
        type: "created",
        title: "Lead Created",
        description: "Referred by Nexkara partner network.",
        timestamp: "FEB 20, 8:30 AM",
      },
    ],
  },
  {
    id: "lead-007",
    leadRef: "L-10027",
    title: "Clearview Café Franchise Rollout",
    status: "New",
    urgency: "Low",
    priority: "Cold",
    contactName: "Tom Adeyemi",
    companyName: "Clearview Café",
    assignedTo: "Kevin Calamari",
    location: "Seattle, WA",
    contactTitle: "Franchise Director",
    customerFor: "Medzah",
    email: "t.adeyemi@clearviewcafe.com",
    phone: "+1 (555) 274-5590",
    validTill: "Mar 31, 2024",
    expectedRevenue: "$18,000",
    grandTotal: "$19,400",
    subject: "Café furniture for 6 new franchise locations",
    opportunityOwner: "Kevin Calamari",
    accountName: "Clearview Franchise Ltd.",
    pipeline: "Sales Pipeline",
    businessType: "B2C",
    leadSource: "Facebook",
    skusQuantity: "6 SKUs / 180 units",
    shippingMethod: "Standard",
    createdDate: "Jan 15, 2024",
    note: "No response since March. Marked inactive.",
    activities: [
      {
        id: "act-016",
        type: "email",
        title: "Follow-up Email",
        description: "Third follow-up with no response.",
        timestamp: "MAR 25, 10:00 AM",
      },
      {
        id: "act-017",
        type: "created",
        title: "Lead Created",
        description: "From email marketing campaign.",
        timestamp: "JAN 15, 9:00 AM",
      },
    ],
  },
];

