import type { Opportunity, QuoteData, QuoteItem } from "@/lib/types";

function qi(
  id: string,
  productName: string,
  quantity: string,
  listPrice: string,
  amount: string
): QuoteItem {
  return { id, productName, quantity, listPrice, amount, description: "" };
}

/** Shared seed quote used by contract “Fetch Data” and list screens */
function luminaQuote(): QuoteData {
  return {
    subject: "OR Suite instrumentation — FY26",
    accountName: "Lumina Architecture",
    businessType: "Existing Business",
    urgency: "High",
    opportunityOwner: "Kevin Calamari",
    opportunityName: "Lumina OR expansion",
    quoteStage: "Delivered",
    validDate: "2026-05-01T12:00:00.000Z",
    contactName: "Alara Kalila",
    shippingMethod: "Freight",
    customerPO: "",
    orderSubmittalMethod: "Email",
    orderNotes: "Dock hours 7am–3pm local.",
    billingStreet: "1200 Peachtree St NE",
    billingCity: "Atlanta",
    billingState: "GA",
    billingCode: "30309",
    billingCountry: "United States",
    shippingStreet: "1200 Peachtree St NE",
    shippingCity: "Atlanta",
    shippingState: "GA",
    shippingCode: "30309",
    shippingCountry: "United States",
    items: [
      qi("li-1", "Surgical display mount (SKU-MNT-441)", "4", "890.00", "3560.00"),
      qi("li-2", "Integrated video hub SKU-HUB-12", "2", "2450.50", "4901.00"),
    ],
    subtotal: "8461.00",
    discount: "100.00",
    tax: "0",
    adjustment: "0",
    grandTotal: "8361.00",
    termsAndConditions: "Net 30. FOB origin.",
    description: "",
    followUpDate: "2026-04-25",
    teamForApproval: ["Amanda", "David Walsh"],
    quoteId: "Q-2026-1001",
  };
}

function meridianQuote(): QuoteData {
  return {
    subject: "Patient monitoring rollout",
    accountName: "Meridian Healthcare Group",
    businessType: "New Business",
    urgency: "Medium",
    opportunityOwner: "Kevin Calamari",
    opportunityName: "Meridian monitoring",
    quoteStage: "Delivered",
    validDate: "2026-06-15T12:00:00.000Z",
    contactName: "Dr. Priya Sharma",
    shippingMethod: "Standard Shipping",
    customerPO: "PO-77821",
    orderSubmittalMethod: "Portal",
    orderNotes: "",
    billingStreet: "500 N Michigan Ave",
    billingCity: "Chicago",
    billingState: "IL",
    billingCode: "60611",
    billingCountry: "United States",
    shippingStreet: "500 N Michigan Ave",
    shippingCity: "Chicago",
    shippingState: "IL",
    shippingCode: "60611",
    shippingCountry: "United States",
    items: [
      qi("li-m1", "Vital signs module SKU-VS-900", "12", "320.00", "3840.00"),
      qi("li-m2", "Nurse station license SKU-NS-LIC", "3", "1100.00", "3300.00"),
    ],
    subtotal: "7140.00",
    discount: "0",
    tax: "0",
    adjustment: "0",
    grandTotal: "7140.00",
    termsAndConditions: "",
    description: "",
    followUpDate: "2026-04-30",
    teamForApproval: ["Denise"],
    quoteId: "Q-2026-1002",
  };
}

function capstoneQuote(): QuoteData {
  return {
    subject: "Consumables pilot",
    accountName: "Capstone Medical",
    businessType: "Existing Business",
    urgency: "Low",
    opportunityOwner: "Kevin Calamari",
    opportunityName: "Capstone consumables",
    quoteStage: "Draft",
    validDate: "2026-07-01T12:00:00.000Z",
    contactName: "Marcus Webb",
    shippingMethod: "Customer Pickup",
    customerPO: "",
    orderSubmittalMethod: "Email",
    orderNotes: "",
    billingStreet: "88 Federal St",
    billingCity: "Boston",
    billingState: "MA",
    billingCode: "02110",
    billingCountry: "United States",
    shippingStreet: "88 Federal St",
    shippingCity: "Boston",
    shippingState: "MA",
    shippingCode: "02110",
    shippingCountry: "United States",
    items: [qi("li-c1", "Sterile kit SKU-SK-55", "50", "12.50", "625.00")],
    subtotal: "625.00",
    discount: "0",
    tax: "0",
    adjustment: "0",
    grandTotal: "625.00",
    termsAndConditions: "",
    description: "",
    followUpDate: "2026-05-15",
    teamForApproval: [],
    quoteId: "Q-2026-1003",
  };
}

export const mockOpportunities: Opportunity[] = [
  {
    id: "opp-seed-lumina",
    opportunityRef: "P-48201",
    opportunityName: "Lumina OR expansion",
    accountName: "Lumina Architecture",
    businessType: "Existing Business",
    closingDate: "2026-05-01",
    contactName: "Alara Kalila",
    contactEmail: "alara.k@lumina.example.com",
    contactPhone: "+1 404-555-0100",
    pipeline: "Medzah Sales Pipeline",
    expectedRevenue: "8361.00",
    amount: "8361.00",
    campaignSource: "Web",
    description: "OR renovation phase 2",
    note: "",
    leadSource: "Direct",
    createdDate: "04/01/26 ; 10:22",
    leadPriority: "Hot",
    opportunityStage: "Closed Won",
    assignedTo: "Kevin Calamari",
    companyName: "Lumina Architecture",
    quoteStatus: "approved",
    quoteData: luminaQuote(),
    activities: [
      {
        id: "act-lum-1",
        type: "created",
        title: "Opportunity created",
        description: "Seed data for CRM demo",
        timestamp: "TODAY",
      },
    ],
  },
  {
    id: "opp-seed-meridian",
    opportunityRef: "P-48202",
    opportunityName: "Meridian monitoring",
    accountName: "Meridian Healthcare Group",
    businessType: "New Business",
    closingDate: "2026-06-15",
    contactName: "Dr. Priya Sharma",
    contactEmail: "priya.sharma@meridian.example.com",
    contactPhone: "+1 312-555-0144",
    pipeline: "Medzah Sales Pipeline",
    expectedRevenue: "7140.00",
    amount: "7140.00",
    campaignSource: "Partner",
    description: "",
    note: "",
    leadSource: "Referral",
    createdDate: "03/20/26 ; 14:05",
    leadPriority: "Warm",
    opportunityStage: "Closed Won",
    assignedTo: "Kevin Calamari",
    companyName: "Meridian Healthcare Group",
    quoteStatus: "approved",
    quoteData: meridianQuote(),
    activities: [
      {
        id: "act-mer-1",
        type: "created",
        title: "Opportunity created",
        description: "Seed data for CRM demo",
        timestamp: "TODAY",
      },
    ],
  },
  {
    id: "opp-seed-capstone",
    opportunityRef: "P-48203",
    opportunityName: "Capstone consumables",
    accountName: "Capstone Medical",
    businessType: "Existing Business",
    closingDate: "2026-07-01",
    contactName: "Marcus Webb",
    contactEmail: "m.webb@capstone.example.com",
    contactPhone: "+1 617-555-0199",
    pipeline: "Medzah Sales Pipeline",
    expectedRevenue: "625.00",
    amount: "625.00",
    campaignSource: "",
    description: "",
    note: "",
    leadSource: "Direct",
    createdDate: "04/10/26 ; 09:00",
    leadPriority: "Cold",
    opportunityStage: "Closed Won",
    assignedTo: "Kevin Calamari",
    companyName: "Capstone Medical",
    quoteStatus: "approved",
    quoteData: capstoneQuote(),
    activities: [
      {
        id: "act-cap-1",
        type: "created",
        title: "Opportunity created",
        description: "Seed data for CRM demo",
        timestamp: "TODAY",
      },
    ],
  },
];
